apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsapi
  labels:
    app: gitopsapi
spec:
  replicas: 3  # Set the desired number of replicas for the application
  selector:
    matchLabels:
      app: gitopsapi
  strategy: {}
  template:
    metadata:
      labels:
        app: gitopsapi
    spec:
      containers:
        - name: gitopsapi
          image: 060213843072.dkr.ecr.us-east-2.amazonaws.com/gitops:latest
          resources: {} 
status: {}          
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: lb-service  # Update this line
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
