apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsapi
  labels:
    app: gitopsapi
spec:
  replicas: 3  # Set the desired number of replicas for the application
  selector:
    matchLabels:
      app: gitopsapi
  template:
    metadata:
      labels:
        app: gitopsapi
    spec:
      containers:
        - name: gitopsapi
          image: 060213843072.dkr.ecr.us-east-2.amazonaws.com/gitops:latest  # Replace with the actual image path in your ECR repository
          ports:
            - containerPort: 8080  # Replace with the port number exposed by the application
          
            # Add more environment variables as needed

# Add any additional resources, volumes, or other configurations specific to your application deployment
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: gitopsapi  # Update this line
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
